// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kboqhvmxppsbpemmcgmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtib3Fodm14cHBzYnBlbW1jZ214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Nzk1NzAsImV4cCI6MjA1ODI1NTU3MH0.8JFH16v_AEqNHQN93tFOXVMPqkz0dPmAo3StyuNsAoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});